---
title: "plot1"
author: "AM"
date: "2026-02-03"
output: html_document
---

```{r}
library(lubridate)
library(dplyr)

df <- read.table(file = "C:\\Users\\amin2\\Desktop\\coursera-notes\\Graphing\\ExData_Plotting1\\exdata_data_household_power_consumption\\household_power_consumption.txt",
           header = TRUE,
           sep = ";",
           na.strings = "?")
```

```{r}
#Data cleaning

#Combine the date and time together

df$datetime <- paste(df$Date, df$Time, sep = " ")

#Need to combined the date and the time into one object
df$datetime <- dmy_hms(df$datetime)

#Cleaning the date
df$Date <- dmy(df$Date)

#Cleaning the time
df$Time <- hms(df$Time)

#All other variables are okay

#Use tolower() since I think the caps are annoying

names(df) <- tolower(names(df))

```

Select only dates between 2007-02-01 and 2007-02-02
```{r}

date1 <- as.Date("2007-02-01")
date2 <- as.Date("2007-02-02")

df <- subset(df, date >= date1 & date <= date2)

write.csv(df, file = "cleaneddata.csv")
```


Plot 1
```{r}
#Frequency vs. Global Active Power

hist(df$global_active_power, col = "red", 
     xlim = c(0, 6), ylim = c(0, 1300),
     xlab = "Global Active Power (kilowatts)",
     main = "Global Active Power")

dev.copy(png, file = "plot1.png", width = 480, height = 480)
dev.off()

```

Plot 2
```{r}

#Global Active Power vs. Day

with(df, plot(datetime, global_active_power,
              xlab = "",
              ylab = "Global Active Power (kilowatts)",
              type = "n", #Don't plot any points
              xaxt = "n")) #Don't plot the native axis, specified below

lines(df$datetime, df$global_active_power, col = "black") #Just add the line
#Add the axis so it's just showing at thursday, friday, and saturday
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))

dev.copy(png, file = "plot2.png", width = 480, height = 480)
dev.off()
```


Plot 3
```{r}
with(df, plot(datetime, sub_metering_1,
              xlab = "",
              ylab = "Energy sub metering",
              xaxt = "n",
              type = "n"))

#Add sub_metering_1
lines(df$datetime, df$sub_metering_1, col = "black")

#Add sub_metering_2
lines(df$datetime, df$sub_metering_2, col = "red")

#Add sub_metering_3
lines(df$datetime, df$sub_metering_3, col = "blue")

#Add axis
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))
legend("topright", col = c("black", "red", "blue"), lty = 1,
       legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))

dev.copy(png, file = "plot3.png", width = 480, height = 480)
dev.off()
```


Plot 4
```{r}
#2 of the plots I've already generated
#Now to generate the other 2

#Voltage vs. datetime

with(df, plot(datetime, voltage,
              type = "n", #don't plot the pch
              xaxt = "n", #don't plot the axis; to specify below
              xlab = "datetime",
              ylab = "Voltage"))
lines(df$datetime, df$voltage, col = "black")
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))

#Global reactive power. vs datetime
with(df, plot(datetime, global_reactive_power,
              xlab = "datetime",
              ylab = "Global_reactive_power",
              type = "n",
              xaxt = "n"))
lines(df$datetime, df$global_reactive_power, col = "black")
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))
```


```{r}

par(mfcol = c(2, 2),
    mar = c(4, 4, 2, 1))

with(df, plot(datetime, global_active_power,
              xlab = "",
              ylab = "Global Active Power (kilowatts)",
              type = "n", #Don't plot any points
              xaxt = "n")) #Don't plot the native axis, specified below

lines(df$datetime, df$global_active_power, col = "black") #Just add the line
#Add the axis so it's just showing at thursday, friday, and saturday
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))

with(df, plot(datetime, sub_metering_1,
              xlab = "",
              ylab = "Energy sub metering",
              xaxt = "n",
              type = "n"))

#Add sub_metering_1
lines(df$datetime, df$sub_metering_1, col = "black")

#Add sub_metering_2
lines(df$datetime, df$sub_metering_2, col = "red")

#Add sub_metering_3
lines(df$datetime, df$sub_metering_3, col = "blue")

#Add axis
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))

with(df, plot(datetime, voltage,
              type = "n", #don't plot the pch
              xaxt = "n", #don't plot the axis; to specify below
              xlab = "datetime",
              ylab = "Voltage"))
lines(df$datetime, df$voltage, col = "black")
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))

#Global reactive power. vs datetime
with(df, plot(datetime, global_reactive_power,
              xlab = "datetime",
              ylab = "Global_reactive_power",
              type = "n",
              xaxt = "n"))
lines(df$datetime, df$global_reactive_power, col = "black")
axis(side = 1, at = pretty(df$datetime), labels = c("Thu", "", "Fri", "", "Sat"))

dev.copy(png, file = "plot4.png", width = 480, height = 480)
dev.off()

```

